
GET http://localhost:8000/funcionario/ HTTP/1.1

###
GET http://localhost:8000/funcionario/10 HTTP/1.1

###
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "Gustavo Vieira Walter",
    "matricula" : "gustavosenha",
    "cpf" : "1",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "ee29eb4a8725678278ac4320e7"
}

### Descobri que precisa dos ### pra separar os testes
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Gustavo Vieira Walter",
    "matricula" : "gustavosenha",
    "cpf" : "1",
    "telefone" : "tel2383738",
    "grupo" : 1,
    "senha" : "dc7378a6b6316017b81c51d720e7"
}

DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1